version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.88.0-node  # Rust + Node.js preinstalled
    steps:
      - checkout
      - run:
          name: Install system dependencies (Debian)
          command: |
            sudo apt update
            sudo apt install libwebkit2gtk-4.0-dev \
              build-essential \
              curl \
              wget \
              file \
              libxdo-dev \
              libssl-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev \
              xdg-utils
      - restore_cache:
          name: Restore node_modules
          keys:
            - v1-npm-cache-{{ checksum "package.json" }}
      - run:
          name: Install frontend dependencies
          command: npm install  # or pnpm install / yarn
      - save_cache:
          name: Cache node_modules 
          paths:
            - ./node_modules
          key: v1-npm-cache-{{ checksum "package.json" }}
      - restore_cache:
          name: Restore cargo (rust packages)
          keys:
            - v1-cargo-cache
      - run:
          name: Build Tauri app
          command: npm run tauri build  # or your custom build command
      - save_cache:
          name: Cache cargo (rust packages)
          paths:
            - ~/.cargo
          key: v1-cargo-cache
      - store_artifacts:
          path: ./src-tauri/target/release/bundle/deb
          destination: deb
      - store_artifacts:
          path: ./src-tauri/target/release/bundle/rpm
          destination: rpm
      - store_artifacts:
          path: ./src-tauri/target/release/bundle/appimage
          destination: appimage