version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.70.0-node  # Rust + Node.js preinstalled
    steps:
      - checkout
      - run:
          name: Install system dependencies (Linux)
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              libwebkit2gtk-4.0-dev \
              build-essential \
              curl \
              wget \
              libssl-dev \
              libgtk-3-dev \
              libayatana-appindicator3-dev
      - run:
          name: Install pnpm (if used)
          command: npm install -g pnpm
      - run:
          name: Install frontend dependencies
          command: npm install  # or pnpm install / yarn
      - run:
          name: Build Tauri app
          command: npm run tauri build  # or your custom build command
      - store_artifacts:
          path: ./src-tauri/target/release
          destination: release