version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.88.0-node
    steps:
      - checkout
      - run:
          name: Install system dependencies (Debian)
          command: |
            sudo apt update
            sudo apt install libwebkit2gtk-4.1-dev \
              build-essential \
              curl \
              wget \
              file \
              libxdo-dev \
              libssl-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev \
              xdg-utils
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install frontend dependencies
          command: npm install
      - run:
          name: Build Tauri app
          command: npm run tauri build
      - save_cache:
          paths:
            - ~/.cargo
            - ./node_modules
          key: v1-cargo-cache-{{ checksum ".circleci/config.yml" }}
      - store_artifacts:
          path: ./src-tauri/target/release/bundle
          destination: release
workflows:
  version: 2
  build_and_test:
    jobs:
      - build